services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3333:3306"
    volumes:
      - db_data:/var/lib/mysql  #ensures that data is persisting and not delted

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: root
volumes:
  db_data: